url: "https://c-square.github.io"
baseurl: ""
title: "C-Square"
description: A virtual proof that name is awesome!
avatar: "/img/avatar-icon.png"

# List of links in the navigation bar
navbar-links:
  Home: ""

# --- Footer options --- #
author:
  name: "C-Square"
  github: "c-square"

# Select which links to show in the footer
footer-links-active:
  rss: true
  facebook: true
  email: false
  twitter: false
  github: true
  linkedin: false
  stackoverflow: false


# Output options (more information on Jekyll's site)
timezone: "Europe/Bucharest"
markdown: redcarpet
highlighter: pygments
permalink: /:year-:month-:day-:title
paginate: 5

# Default YAML values (more information on Jekyll's site)
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      comments: true  # add comments to all blog posts
  -
    scope:
      path: "" # all files
    values:
      layout: "default"

# Exclude these files from production site
exclude:
  - LICENSE
  - README.md
  - .gitignore
